#include "SoundFX.h"

#include <mad.h>
#include <asndlib.h>
#include <ogc/cache.h>
#include <ogc/lwp_watchdog.h>
#include <malloc.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <vector>

/* -----------------------------------------------------------------------
 * Embedded MP3 data (generated by xxd in the Makefile)
 * ----------------------------------------------------------------------- */
extern unsigned char data_sounds_start_mp3[];
extern unsigned int  data_sounds_start_mp3_len;
extern unsigned char data_sounds_select_mp3[];
extern unsigned int  data_sounds_select_mp3_len;
extern unsigned char data_sounds_press_key_mp3[];
extern unsigned int  data_sounds_press_key_mp3_len;
extern unsigned char data_sounds_menu_exit_mp3[];
extern unsigned int  data_sounds_menu_exit_mp3_len;
extern unsigned char data_sounds_menu_enter_mp3[];
extern unsigned int  data_sounds_menu_enter_mp3_len;
extern unsigned char data_sounds_loading_mp3[];
extern unsigned int  data_sounds_loading_mp3_len;
extern unsigned char data_sounds_backspace_mp3[];
extern unsigned int  data_sounds_backspace_mp3_len;
extern unsigned char data_sounds_back_mp3[];
extern unsigned int  data_sounds_back_mp3_len;

/* -----------------------------------------------------------------------
 * ASND voice slots — keep away from MP3Player which uses voices 0–1.
 * ----------------------------------------------------------------------- */
static const int      FX_VOICE        = 4;   /* one-shot sound effects             */
static const int      LOAD_VOICE      = 5;   /* looping loading sound              */
static const int      MENU_VOICE      = 6;   /* MenuEnter/MenuExit — dedicated slot */
static const int      FX_VOL          = 200; /* 0–255                              */
static const uint64_t FX_COOLDOWN_MS  = 150;  /* minimum interval between same-FX   */

/* Per-FX last-play timestamp (ms); 0 = never played, so first play always works */
static uint64_t s_fxLastPlayMs[(int)SoundFX::FX::COUNT_] = {};

/* Per-FX gain applied during PCM decode (1.0 = unity; <1.0 = attenuate).
 * Apply here — before the int16 clamp — so loud sources don't clip.
 * Order must match enum FX { Start, Select, PressKey, MenuExit, MenuEnter,
 *                            Loading, Backspace, Back }. */
static const float FX_GAIN[(int)SoundFX::FX::COUNT_] = {
    0.40f,  /* Start     — source is very loud; reduce to prevent clipping */
    1.0f,   /* Select    */
    1.0f,   /* PressKey  */
    1.0f,   /* MenuExit  */
    1.0f,   /* MenuEnter */
    1.0f,   /* Loading   */
    1.0f,   /* Backspace */
    1.0f,   /* Back      */
};

/* -----------------------------------------------------------------------
 * PCM buffer descriptor
 * ----------------------------------------------------------------------- */
struct PcmBuf {
    void*        data;     /* memalign(32) PCM buffer, cache-flushed */
    unsigned int byteLen;  /* byte length of valid PCM data          */
    int          pitch;    /* sample rate in Hz                      */
    int          format;   /* VOICE_STEREO_16BIT or VOICE_MONO_16BIT */
};

static PcmBuf   s_fx[(int)SoundFX::FX::COUNT_] = {};

/* Earliest time (ms) at which tickLoading() is allowed to restart the voice.
 * Computed from the actual decoded buffer duration so the restart is gated on
 * the real playback length, not on ASND's async status flag. */
static uint64_t s_loadReadyMs = 0;

/* -----------------------------------------------------------------------
 * decodeMp3 — decode an MP3 buffer into a 32-byte-aligned PCM buffer
 *             using libmad.  Returns an empty PcmBuf on failure.
 * ----------------------------------------------------------------------- */
static PcmBuf decodeMp3(const unsigned char* mp3Data, unsigned int mp3Len,
                        float gain = 1.0f)
{
    /* Pre-compute gain in Q1.28 (same domain as mad_fixed_t = int32_t Q1.28). */
    const mad_fixed_t gainQ28 = (mad_fixed_t)((double)gain * (double)MAD_F_ONE);
    PcmBuf result = {};
    if (!mp3Data || !mp3Len) return result;

    std::vector<int16_t> tmp;
    tmp.reserve(mp3Len * 8); /* rough upper-bound estimate */

    struct mad_stream stream;
    struct mad_frame  frame;
    struct mad_synth  synth;
    mad_stream_init(&stream);
    mad_frame_init(&frame);
    mad_synth_init(&synth);

    mad_stream_buffer(&stream, mp3Data, mp3Len);

    unsigned int sampleRate = 44100;
    int          channels   = 2;
    bool         gotHeader  = false;

    for (;;) {
        if (mad_frame_decode(&frame, &stream) == -1) {
            if (stream.error == MAD_ERROR_BUFLEN || !MAD_RECOVERABLE(stream.error))
                break;
            continue;
        }
        if (!gotHeader) {
            sampleRate = frame.header.samplerate;
            channels   = (frame.header.mode == MAD_MODE_SINGLE_CHANNEL) ? 1 : 2;
            gotHeader  = true;
        }
        mad_synth_frame(&synth, &frame);

        const struct mad_pcm& pcm = synth.pcm;
        for (unsigned int i = 0; i < pcm.length; ++i) {
            /* Left / mono channel */
            mad_fixed_t s = pcm.samples[0][i];
            /* Apply gain before the clamp so loud sources don't saturate. */
            if (gainQ28 != MAD_F_ONE)
                s = (mad_fixed_t)(((int64_t)s * gainQ28) >> MAD_F_FRACBITS);
            if (s >=  MAD_F_ONE) s =  MAD_F_ONE - 1;
            if (s < -MAD_F_ONE)  s = -MAD_F_ONE;
            tmp.push_back((int16_t)(s >> (MAD_F_FRACBITS - 15)));

            /* Right channel (or duplicate left for forced-stereo mono input) */
            if (channels == 2) {
                s = pcm.samples[1][i];
                if (gainQ28 != MAD_F_ONE)
                    s = (mad_fixed_t)(((int64_t)s * gainQ28) >> MAD_F_FRACBITS);
                if (s >=  MAD_F_ONE) s =  MAD_F_ONE - 1;
                if (s < -MAD_F_ONE)  s = -MAD_F_ONE;
                tmp.push_back((int16_t)(s >> (MAD_F_FRACBITS - 15)));
            }
        }
    }

    mad_synth_finish(&synth);
    mad_frame_finish(&frame);
    mad_stream_finish(&stream);

    if (tmp.empty()) return result;

    unsigned int byteLen    = (unsigned int)tmp.size() * sizeof(int16_t);
    unsigned int alignedLen = (byteLen + 31u) & ~31u;
    void* buf = memalign(32, alignedLen);
    if (!buf) return result;

    memset(buf, 0, alignedLen);
    memcpy(buf, tmp.data(), byteLen);
    DCFlushRange(buf, alignedLen); /* ensure DSP sees the data */

    result.data    = buf;
    result.byteLen = byteLen;
    result.pitch   = (int)sampleRate;
    result.format  = (channels == 2) ? VOICE_STEREO_16BIT : VOICE_MONO_16BIT;
    return result;
}

/* -----------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */
void SoundFX::init()
{
    /* Source table — order must match enum FX { Start, Select, ... } */
    struct Src { const unsigned char* data; unsigned int len; };
    const Src srcs[(int)FX::COUNT_] = {
        { data_sounds_start_mp3,      data_sounds_start_mp3_len      }, /* Start     */
        { data_sounds_select_mp3,     data_sounds_select_mp3_len     }, /* Select    */
        { data_sounds_press_key_mp3,  data_sounds_press_key_mp3_len  }, /* PressKey  */
        { data_sounds_menu_exit_mp3,  data_sounds_menu_exit_mp3_len  }, /* MenuExit  */
        { data_sounds_menu_enter_mp3, data_sounds_menu_enter_mp3_len }, /* MenuEnter */
        { data_sounds_loading_mp3,    data_sounds_loading_mp3_len    }, /* Loading   */
        { data_sounds_backspace_mp3,  data_sounds_backspace_mp3_len  }, /* Backspace */
        { data_sounds_back_mp3,       data_sounds_back_mp3_len       }, /* Back      */
    };

    for (int i = 0; i < (int)FX::COUNT_; ++i) {
        s_fx[i] = decodeMp3(srcs[i].data, srcs[i].len, FX_GAIN[i]);

        /* Trim leading silence (MP3 encoder pre-roll padding, typically ~13 ms
         * of mathematically exact zeros produced by LAME).
         * Use a low -48 dB threshold (|v| >= 128) so that only true encoder
         * silence is skipped — sounds with soft attacks (e.g. menu_exit) are
         * preserved from the first audible sample.  A -24 dB threshold was
         * previously used but it cut 8–9 ms of actual soft-attack content.
         * Step back 8 samples to keep the transient, then round down to a
         * 32-byte cache-line boundary. */
        PcmBuf& b = s_fx[i];
        if (b.data && b.byteLen >= 64) {
            const int16_t* pcm   = (const int16_t*)b.data;
            unsigned int   n     = b.byteLen / sizeof(int16_t);
            unsigned int   first = 0; /* stays 0 if no silence found */
            for (unsigned int s = 0; s < n; ++s) {
                if (pcm[s] > 128 || pcm[s] < -128) {
                    first = (s > 8) ? s - 8 : 0;
                    break;
                }
            }
            unsigned int skip = (first * (unsigned int)sizeof(int16_t)) & ~31u;
            if (skip > 0 && skip < b.byteLen) {
                b.data    = (uint8_t*)b.data + skip;
                b.byteLen -= skip;
                /* Re-flush so the DSP DMA reads from the new aligned start. */
                DCFlushRange(b.data, (b.byteLen + 31u) & ~31u);
            }
        }
    }
}

void SoundFX::play(FX fx)
{
    int idx = (int)fx;
    if (idx < 0 || idx >= (int)FX::COUNT_) return;

    const PcmBuf& b = s_fx[idx];
    if (!b.data || !b.byteLen) return;

    if (fx == FX::Loading) {
        /* Arm the loop — actual playback starts (and re-starts) via tickLoading(). */
        ASND_StopVoice(LOAD_VOICE);
        s_loadReadyMs = 0; /* allow tickLoading() to fire immediately */
    } else {
        uint64_t nowMs = ticks_to_millisecs(gettime());

        /* MenuEnter and MenuExit use their own dedicated voice so they are
         * never dropped because FX_VOICE is busy with a hover/key sound.
         * They are also exempt from the cooldown so the sound always plays
         * even if the menu is opened/closed rapidly. */
        const bool  isMenu = (fx == FX::MenuEnter || fx == FX::MenuExit);

        /* Per-FX cooldown: skip if this exact sound played recently.
         * Prevents rapid-hover spam and back-to-back retrigger glitches.
         * Not applied to menu sounds which must always play. */
        if (!isMenu) {
            if (nowMs - s_fxLastPlayMs[idx] < FX_COOLDOWN_MS) return;
            s_fxLastPlayMs[idx] = nowMs;
        }
        const int   voice  = isMenu ? MENU_VOICE : FX_VOICE;

        /* Stop the voice, then spin-wait for ASND to reach SND_UNUSED.
         * ASND_StopVoice is asynchronous — the DSP processes it on its next
         * callback (~5 ms).  If ASND_SetVoice is called while the voice is
         * still in SND_STOPPING it returns SND_BUSY and silently discards the
         * play request — causing the "sound doesn't start" symptom.
         * 40 × 500 µs = 20 ms maximum wait; always well within one frame. */
        ASND_StopVoice(voice);
        for (int i = 0; i < 40 && ASND_StatusVoice(voice) != SND_UNUSED; i++)
            usleep(500);

        ASND_SetVoice(voice, b.format, b.pitch, 0,
                      b.data, (int)b.byteLen, FX_VOL, FX_VOL, nullptr);
    }
}

void SoundFX::waitDone(FX fx)
{
    const bool isMenu = (fx == FX::MenuEnter || fx == FX::MenuExit);
    const int  voice  = isMenu ? MENU_VOICE : FX_VOICE;
    /* ASND_SetVoice is asynchronous — give the DSP one callback cycle (~5 ms)
     * to actually start the voice before we start polling for idle. */
    usleep(30000);
    /* Then spin-wait up to ~1 s (200 × 5 ms) for playback to finish. */
    for (int i = 0; i < 200 && ASND_StatusVoice(voice) != SND_UNUSED; i++)
        usleep(5000);
}

void SoundFX::tickLoading()
{
    const PcmBuf& b = s_fx[(int)FX::Loading];
    if (!b.data || !b.byteLen || !b.pitch) return;

    /* Gate: don't restart before the buffer has had time to finish.
     * ASND_SetVoice is asynchronous — StatusVoice can still read SND_UNUSED
     * for one or more frames after the call, causing a rapid-restart loop.
     * We compute the exact duration from the buffer size and only allow a
     * restart once that wall-clock time has elapsed. */
    uint64_t nowMs = ticks_to_millisecs(gettime());
    if (nowMs < s_loadReadyMs) return;

    /* Also confirm the voice is actually idle before touching it. */
    if (ASND_StatusVoice(LOAD_VOICE) != SND_UNUSED) return;

    /* Compute duration and schedule the next earliest restart. */
    int      bps      = (b.format == VOICE_STEREO_16BIT) ? 4 : 2;
    uint64_t durMs    = ((uint64_t)b.byteLen * 1000ULL)
                        / ((uint64_t)b.pitch * (uint64_t)bps);
    s_loadReadyMs = nowMs + durMs;

    ASND_SetVoice(LOAD_VOICE, b.format, b.pitch, 0,
                  b.data, (int)b.byteLen, FX_VOL, FX_VOL, nullptr);
}

void SoundFX::stopLoading()
{
    ASND_StopVoice(LOAD_VOICE);
}
